-- This script only contains the table creation statements and does not fully represent the table in database. It's still missing: indices, triggers. Do not use it as backup.

-- Squences
CREATE SEQUENCE IF NOT EXISTS bus_id_seq1

-- Table Definition
CREATE TABLE "public"."bus" (
    "id" int4 NOT NULL DEFAULT nextval('bus_id_seq1'::regclass),
    "related_to" varchar,
    "tx_id" varchar,
    "ao_id" varchar,
    "source" varchar,
    "status" varchar,
    "url" text,
    "departure" timestamp,
    "parent" varchar,
    "next" varchar,
    "previous" varchar,
    "path" text,
    "payload" text,
    "created_at" timestamp,
    "updated_at" timestamp,
    "result" text,
    "picked" timestamp,
    "received" timestamp,
    PRIMARY KEY ("id")
);

INSERT INTO "public"."bus" ("id", "related_to", "tx_id", "ao_id", "source", "status", "url", "departure", "parent", "next", "previous", "path", "payload", "created_at", "updated_at", "result", "picked", "received") VALUES
(779, 'orderService', 'tx_yzgyqtkxtmrisgnxhfjkcrzwn', 'ao_yzpmvbplgsgcvsndasidoanxnoefpmryxnkhcjpwzortfdprnimaqtatqvvjkbkqq', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_yzpmvbplgsgcvsndasidoanxnoefpmryxnkhcjpwzortfdprnimaqtatqvvjkbkqq', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."bus" ("id", "related_to", "tx_id", "ao_id", "source", "status", "url", "departure", "parent", "next", "previous", "path", "payload", "created_at", "updated_at", "result", "picked", "received") VALUES
(796, 'shipmentService', 'tx_fmsejkxrtacqqdbcyngvlvqpv', 'ao_rnswbmclzbdfdvgayyptaxljmoobflmtopwkbxccrelgkytksqiqqoeyrnyolvnlo', 'shipment', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_idxxszrfrlcafyjncyzkjsqaacyrwbfpszillixbkfdgqagvoecacbakinprssyjg', NULL, 'ao_vocijyrzdonlfyveeikqriqympovmnskzicikteonpkoeohvxhvboyshwiiooytol', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."bus" ("id", "related_to", "tx_id", "ao_id", "source", "status", "url", "departure", "parent", "next", "previous", "path", "payload", "created_at", "updated_at", "result", "picked", "received") VALUES
(797, 'orderService', 'tx_jtmggicrgcqpzwqtqhoodlwfw', 'ao_ckqpijclobdoygyzcdhiwergbzmzkrwffdalizlyxjwxdqmyhkfwexectcdthwnny', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_ckqpijclobdoygyzcdhiwergbzmzkrwffdalizlyxjwxdqmyhkfwexectcdthwnny', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "public"."bus" ("id", "related_to", "tx_id", "ao_id", "source", "status", "url", "departure", "parent", "next", "previous", "path", "payload", "created_at", "updated_at", "result", "picked", "received") VALUES
(798, 'orderService', 'tx_arfzwgysqyfgfqixersrhbylj', 'ao_mtvcdcsrnhmfoljozfqeblxoclbcwpcvlggpwserhnpqvlpdfkxkbaelcoftfqxmk', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_mtvcdcsrnhmfoljozfqeblxoclbcwpcvlggpwserhnpqvlpdfkxkbaelcoftfqxmk', 'ao_ozwpyxvgdftrmoggshtzmmbsmarmftwvhkercztyjwopfpinadxgzhbggmbknamle', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(801, 'orderService', 'tx_pbnocnorlpyegwjmddpfbjjjp', 'ao_xvsoczagznosprpckeifirnepqvglknfekrejwgfmpjvjitissiafoypzrhvenpzl', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_xvsoczagznosprpckeifirnepqvglknfekrejwgfmpjvjitissiafoypzrhvenpzl', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(802, 'orderService', 'tx_hgvzmvqeyzlvirpsknbrbgksz', 'ao_oybvltgcsbntlownrybgfxlighmqrfmfpehnxpscnzedmnyeyctzoczfjrhtkmroc', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_oybvltgcsbntlownrybgfxlighmqrfmfpehnxpscnzedmnyeyctzoczfjrhtkmroc', 'ao_dtqzgojytsocpxotzrnikkabaddeoznbvfjtpimzxenxnwhcxjsnzgmskjfjrferd', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(803, 'paymentService', 'tx_hgvzmvqeyzlvirpsknbrbgksz', 'ao_dtqzgojytsocpxotzrnikkabaddeoznbvfjtpimzxenxnwhcxjsnzgmskjfjrferd', 'payment', 'new', 'string', NULL, 'ao_oybvltgcsbntlownrybgfxlighmqrfmfpehnxpscnzedmnyeyctzoczfjrhtkmroc', 'ao_tdfajephwrelwyoxjyzzlcorsqnatjwebvovqyajtggjxberttaqcbakypecgfnzl', 'ao_oybvltgcsbntlownrybgfxlighmqrfmfpehnxpscnzedmnyeyctzoczfjrhtkmroc', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, NULL, NULL, NULL),
(804, 'shipmentService', 'tx_hgvzmvqeyzlvirpsknbrbgksz', 'ao_tdfajephwrelwyoxjyzzlcorsqnatjwebvovqyajtggjxberttaqcbakypecgfnzl', 'shipment', 'new', 'string', NULL, 'ao_oybvltgcsbntlownrybgfxlighmqrfmfpehnxpscnzedmnyeyctzoczfjrhtkmroc', NULL, 'ao_dtqzgojytsocpxotzrnikkabaddeoznbvfjtpimzxenxnwhcxjsnzgmskjfjrferd', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, NULL, NULL, NULL),
(805, '${sql.L(message.related_to)}', '${sql.L(tx_id)}', '${sql.L(message.ao_id)}', '${sql.L(message.source)}', '${sql.L(status)}', '2022-01-20', '2022-01-20 00:00:00', '${sql.L(parent)}', '${sql.L(message.next)}', '${sql.L(message.previous)}', '${sql.L(message.path)}', '${sql.L(JSON.stringify(message.payload || {}))}', NULL, NULL, NULL, NULL, NULL),
(806, 'orderService', 'tx_eyeinlsbzcsrwtjjzytwzkakn', 'ao_yvagnijkjmwhxhxkdhwemwktllgnimlhtiytjhdxxhzitrcgeydthhkjjmrzcbkvy', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_yvagnijkjmwhxhxkdhwemwktllgnimlhtiytjhdxxhzitrcgeydthhkjjmrzcbkvy', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(809, 'shipmentService', 'tx_amdafwphlqdbdprqvktnpryjt', 'ao_dtfnnhwjlgflnwbnmrqhlbbbofhowmwmlpfjwryzzjqdeboshdkqjssipaelspoqr', 'shipment', 'new', 'string', NULL, 'ao_ltexrzfdspdxnfebwelqqxfosneehrogiiclhsnaomghwxvjijdmhvvjyyxcpjlps', NULL, 'ao_nibqyeeldksoqyvqnaabsfktbfxzezqfqlbdkdzraoedbqeyesrvcslbbznjldwfw', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, NULL, NULL, NULL),
(810, 'orderService', 'tx_vnfgcivmhvtdefxcopeklgyls', 'ao_jeshtprmzejjcpozekskccypjtwewtrbwvkhlxpalrlwvovzaaijxjkrvkhfmyxva', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_jeshtprmzejjcpozekskccypjtwewtrbwvkhlxpalrlwvovzaaijxjkrvkhfmyxva', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(811, 'orderService', 'tx_rvwancmxotbyiejvpnddggpif', 'ao_qgssdficvqivnqjjnlbapdwatkepwgjygtkffwwbtzzitxkkgoiopakyrofpbhwjv', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_qgssdficvqivnqjjnlbapdwatkepwgjygtkffwwbtzzitxkkgoiopakyrofpbhwjv', 'ao_pekownegzxymyaaobrxnsrqvpaozgejhwwmdmayqklcbevylaqwvdlwexmeabocdh', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(812, 'paymentService', 'tx_rvwancmxotbyiejvpnddggpif', 'ao_pekownegzxymyaaobrxnsrqvpaozgejhwwmdmayqklcbevylaqwvdlwexmeabocdh', 'payment', 'new', 'string', NULL, 'ao_qgssdficvqivnqjjnlbapdwatkepwgjygtkffwwbtzzitxkkgoiopakyrofpbhwjv', 'ao_gyeilmrlhvhapcgxdgcesmgezdbcxrfpxmyqflbpjnwpvfiyfxnevdzjpsxwakjpl', 'ao_qgssdficvqivnqjjnlbapdwatkepwgjygtkffwwbtzzitxkkgoiopakyrofpbhwjv', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, NULL, NULL, NULL),
(793, 'orderService', 'tx_joeoqlvsxnmcobrdezgoiiswz', 'ao_ldmrbhirjdnytmhmannoocijrqtrcptwrvpjoejcjplgsxciwhdrjtcexyhaokwni', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_ldmrbhirjdnytmhmannoocijrqtrcptwrvpjoejcjplgsxciwhdrjtcexyhaokwni', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, 'test', NULL, NULL),
(799, 'paymentService', 'tx_arfzwgysqyfgfqixersrhbylj', 'ao_ozwpyxvgdftrmoggshtzmmbsmarmftwvhkercztyjwopfpinadxgzhbggmbknamle', 'payment', 'done', 'string', NULL, 'ao_mtvcdcsrnhmfoljozfqeblxoclbcwpcvlggpwserhnpqvlpdfkxkbaelcoftfqxmk', 'ao_ihhqjmvxdzzsvaavdzzbypabggdghrwacmzcygpwyzryoldrpvgtgxyqfgiwlwnep', 'ao_mtvcdcsrnhmfoljozfqeblxoclbcwpcvlggpwserhnpqvlpdfkxkbaelcoftfqxmk', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, '"Done properly"', NULL, '2022-04-17 21:39:26.874079'),
(794, 'orderService', 'tx_fmsejkxrtacqqdbcyngvlvqpv', 'ao_idxxszrfrlcafyjncyzkjsqaacyrwbfpszillixbkfdgqagvoecacbakinprssyjg', 'order', 'done', 'string', '2022-04-15 18:00:00', 'ao_idxxszrfrlcafyjncyzkjsqaacyrwbfpszillixbkfdgqagvoecacbakinprssyjg', 'ao_vocijyrzdonlfyveeikqriqympovmnskzicikteonpkoeohvxhvboyshwiiooytol', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, '{"message":"Successfully placed order","orderId":145711}', NULL, '2022-04-17 21:39:26.596873'),
(807, 'orderService', 'tx_amdafwphlqdbdprqvktnpryjt', 'ao_ltexrzfdspdxnfebwelqqxfosneehrogiiclhsnaomghwxvjijdmhvvjyyxcpjlps', 'order', 'received', 'string', '2022-04-15 18:00:00', 'ao_ltexrzfdspdxnfebwelqqxfosneehrogiiclhsnaomghwxvjijdmhvvjyyxcpjlps', 'ao_nibqyeeldksoqyvqnaabsfktbfxzezqfqlbdkdzraoedbqeyesrvcslbbznjldwfw', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, '{"__debug":{"messageNaN":{"__debug":"Hello world"}}}', NULL, '2022-04-17 21:39:26.764835'),
(808, 'paymentService', 'tx_amdafwphlqdbdprqvktnpryjt', 'ao_nibqyeeldksoqyvqnaabsfktbfxzezqfqlbdkdzraoedbqeyesrvcslbbznjldwfw', 'payment', 'consumable', 'string', NULL, 'ao_ltexrzfdspdxnfebwelqqxfosneehrogiiclhsnaomghwxvjijdmhvvjyyxcpjlps', 'ao_dtfnnhwjlgflnwbnmrqhlbbbofhowmwmlpfjwryzzjqdeboshdkqjssipaelspoqr', 'ao_ltexrzfdspdxnfebwelqqxfosneehrogiiclhsnaomghwxvjijdmhvvjyyxcpjlps', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, NULL, NULL, NULL),
(813, 'shipmentService', 'tx_rvwancmxotbyiejvpnddggpif', 'ao_gyeilmrlhvhapcgxdgcesmgezdbcxrfpxmyqflbpjnwpvfiyfxnevdzjpsxwakjpl', 'shipment', 'new', 'string', NULL, 'ao_qgssdficvqivnqjjnlbapdwatkepwgjygtkffwwbtzzitxkkgoiopakyrofpbhwjv', NULL, 'ao_pekownegzxymyaaobrxnsrqvpaozgejhwwmdmayqklcbevylaqwvdlwexmeabocdh', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, NULL, NULL, NULL),
(814, 'test', '23121', 'ao_lrwxbsiprptvjnnoapxokpwozqqeradllivjsnvegqmqxseacydxpevqfjdgjadcz', 'arr3434', 'consumable', 'string', '2022-01-01 18:00:00', '53wdeqw', NULL, NULL, 'string', '321313131', NULL, NULL, NULL, NULL, NULL),
(815, 'test', '23121', 'ao_bbirkmtlaljepzypfnvctpkcqnbjxbeffhhkgkgidjtzrbtosklpcyhzwoovrlmwe', 'arr3434', 'consumable', 'string', '2022-01-01 18:00:00', '53wdeqw', NULL, NULL, 'string', '321313131', NULL, NULL, NULL, NULL, NULL),
(816, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(817, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(818, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(819, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(820, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(821, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(822, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(823, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(824, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(825, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(826, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(827, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(828, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(829, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(830, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(795, 'paymentService', 'tx_fmsejkxrtacqqdbcyngvlvqpv', 'ao_vocijyrzdonlfyveeikqriqympovmnskzicikteonpkoeohvxhvboyshwiiooytol', 'payment', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_idxxszrfrlcafyjncyzkjsqaacyrwbfpszillixbkfdgqagvoecacbakinprssyjg', 'ao_rnswbmclzbdfdvgayyptaxljmoobflmtopwkbxccrelgkytksqiqqoeyrnyolvnlo', 'ao_idxxszrfrlcafyjncyzkjsqaacyrwbfpszillixbkfdgqagvoecacbakinprssyjg', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, NULL, NULL, NULL),
(837, 'orderService', 'tx_qyntcmjacypdijoefokwrjsdr', 'ao_dznnkfdqthsvvyydwficpnvloddjvprmjwmbdhdmnzqxrbsaqrkijzyapoalhafsq', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_dznnkfdqthsvvyydwficpnvloddjvprmjwmbdhdmnzqxrbsaqrkijzyapoalhafsq', NULL, NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(831, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(832, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(833, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(838, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(839, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(834, 'order', '12345', '1235678', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235679', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(835, 'order', '12345', '1235679', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '1235680', '1235678', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(836, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(840, 'order', '12345', '1235680', 'order', NULL, 'http://test.com', '2021-12-31 18:00:00', '123', '125666', '125661', 'orderPayment', 'Hello world', NULL, NULL, NULL, NULL, NULL),
(841, 'orderService', 'tx_djxqlltgdfhejocrnxfahiien', 'ao_gtmnitfoyhpddpldrihvivafbwyflnzampbhihjsfdrmzaofgmrhrtbmxyvbfdlfm', 'order', 'consumable', 'string', '2022-04-15 18:00:00', 'ao_gtmnitfoyhpddpldrihvivafbwyflnzampbhihjsfdrmzaofgmrhrtbmxyvbfdlfm', 'ao_oevpfmokqqxxnerfsgnbdgrtkddlywklqgfvoqpzlndoyqdztppjawwfhqxbjiemq', NULL, 'orderApp', '{"quantity":10,"productId":111}', NULL, NULL, NULL, NULL, NULL),
(800, 'shipmentService', 'tx_arfzwgysqyfgfqixersrhbylj', 'ao_ihhqjmvxdzzsvaavdzzbypabggdghrwacmzcygpwyzryoldrpvgtgxyqfgiwlwnep', 'shipment', 'consumable', 'string', '2022-04-18 03:40:26.886', 'ao_mtvcdcsrnhmfoljozfqeblxoclbcwpcvlggpwserhnpqvlpdfkxkbaelcoftfqxmk', NULL, 'ao_ozwpyxvgdftrmoggshtzmmbsmarmftwvhkercztyjwopfpinadxgzhbggmbknamle', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, '"hello world"', NULL, '2022-04-17 21:39:26.89036'),
(842, 'paymentService', 'tx_djxqlltgdfhejocrnxfahiien', 'ao_oevpfmokqqxxnerfsgnbdgrtkddlywklqgfvoqpzlndoyqdztppjawwfhqxbjiemq', 'payment', 'new', 'string', NULL, 'ao_gtmnitfoyhpddpldrihvivafbwyflnzampbhihjsfdrmzaofgmrhrtbmxyvbfdlfm', 'ao_jlcvocqpsvzqnconklkaiflfthslqdohlvpabilkdkajombwrzlorpcvhksoznhby', 'ao_gtmnitfoyhpddpldrihvivafbwyflnzampbhihjsfdrmzaofgmrhrtbmxyvbfdlfm', 'paymentApp', '{"sellingPrice":1000,"liftingPrice":800}', NULL, NULL, NULL, NULL, NULL),
(843, 'shipmentService', 'tx_djxqlltgdfhejocrnxfahiien', 'ao_jlcvocqpsvzqnconklkaiflfthslqdohlvpabilkdkajombwrzlorpcvhksoznhby', 'shipment', 'new', 'string', NULL, 'ao_gtmnitfoyhpddpldrihvivafbwyflnzampbhihjsfdrmzaofgmrhrtbmxyvbfdlfm', NULL, 'ao_oevpfmokqqxxnerfsgnbdgrtkddlywklqgfvoqpzlndoyqdztppjawwfhqxbjiemq', 'shipmentApp', '{"address":"House 39 Road 7 Hamilton road"}', NULL, NULL, NULL, NULL, NULL),
(844, 'test', '23121', 'ao_xpqmvntlfrstehyxnebxtneypcyhtblwnhwjlzbwkrthazhcyiaqrobvdybtnbgxs', 'arr3434', 'consumable', 'string', '2022-01-01 18:00:00', '53wdeqw', NULL, NULL, 'string', '321313131', NULL, NULL, NULL, NULL, NULL);